{
 "title": "Metrics API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Most frequently accessed endpoints (top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (increase(http_server_requests_seconds_count{instance=\"calc-application-db:8081\"}[5m])) > 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(method, uri, status) (http_server_requests_active_seconds_count{instance=\"calc-application-db:8081\", method=\"GET\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second (throughput)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(method, status, uri) (rate(http_server_requests_seconds_count{instance=\"calc-application-db:8081\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(status, method, uri) (rate(http_server_requests_seconds_sum{instance=\"calc-application-db:8081\"}[$__rate_interval])) / sum by(status, method, uri) (rate(http_server_requests_seconds_count{instance=\"calc-application-db:8081\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP error rate (4xx and 5xx) over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "__auto" }
   ]
  }
 ]
}