GRANT CONNECT ON DATABASE calculadora_db TO calcUserDB;

GRANT USAGE ON SCHEMA public TO calcUserDB;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES
    IN SCHEMA public TO calcUserDB;

GRANT USAGE, SELECT ON ALL SEQUENCES
    IN SCHEMA public TO calcUserDB;

GRANT EXECUTE ON ALL FUNCTIONS
IN SCHEMA public TO calcUserDB;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO calcUserDB;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT EXECUTE ON FUNCTIONS TO calcUserDB;

GRANT SELECT, INSERT ON CalculationHistory TO calcUserDB;
GRANT SELECT, INSERT, UPDATE ON UserOperations TO calcUserDB;

\dp public.*