spring:
  application:
    name: CalculadoraMicroServicesDB
  config:
    import: "vault://secret/calcDbSecrets"
  cloud:
    vault:
      authentication: TOKEN
      connection-timeout: 5000
      kv:
        enabled: true
        backend: secret
        default-context: calcDbSecrets
        application-name: CalculadoraMicroServicesDB
        profile-separator: /

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    defer-datasource-initialization: true

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true

admin:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    defer-datasource-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
          enabled: true

server:
  port: 8081
