spring:
  application:
    name: CalculadoraMicroServicesDB
  config:
    import: "vault://secret/calcDbSecrets"
  cloud:
    vault:
      uri: ${VAULT_APPLICATION_ADDR}
      token: ${VAULT_TOKEN}
      authentication: TOKEN
      connection-timeout: 5000
      kv:
        enabled: true
        backend: secret
        default-context: calcDbSecrets
        application-name: CalculadoraMicroServicesDB
        profile-separator: /


  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    defer-datasource-initialization: true

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true

server:
  port: 8081
