{
 "title": "Banco de Dados MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Operações inseridas por minuto (volume de cálculos realizados)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tempo médio de execução das queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(instance, job) (rate(mysql_global_status_queries{instance=\"mysql-exporter:9104\", job=\"mysql-calc\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries com erro",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance, job) (rate(mysql_global_status_connection_errors_total{job=\"mysql-calc\", instance=\"mysql-exporter:9104\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tamanho da tabela OPERATIONS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(__name__, instance, job) (mysql_global_variables_max_heap_table_size{instance=\"mysql-exporter:9104\", job=\"mysql-calc\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conexões ativas no pool HikariCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(instance, job, pool) (hikaricp_connections{instance=\"calc-application-db:8081\", job=\"calc-application-db\", pool=\"HikariPool-1\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}