{
 "title": "JVM e Performance Application",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Conexões abertas no HikariCP (pool de conexões)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance, pool) (hikaricp_connections{instance=\"calc-application-db:8081\", pool=\"HikariPool-1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de memória heap virtual",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(jvm_memory_committed_bytes{instance=\"calc-application-db:8081\", area=\"heap\"}[$__rate_interval])) * 100) / (sum by(instance) (jvm_memory_committed_bytes{instance=\"calc-application-db:8081\", area=\"heap\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(process_cpu_usage{instance=\"calc-application-db:8081\"}[5m])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads ativas vs threads em espera",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=\"calc-application-db:8081\",job=\"calc-application-db\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"waiting\", instance=\"calc-application-db:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de memória heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (jvm_memory_used_bytes{instance=\"calc-application-db:8081\", area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collection Total time executed (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(instance, gc) (rate(jvm_gc_pause_seconds_sum{instance=\"calc-application-db:8081\", gc=\"G1 Young Generation\"}[$__rate_interval])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}