{
 "title": "Vault Application",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Latência das respostas do Vault",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(avg by(service, route, method, instance, job) (rate(vault_core_handle_request_sum{instance=\"vault-calc:8200\", job=\"vault-calc\"}[$__rate_interval]) * 1000000)) / (rate(vault_core_handle_request_count{instance=\"vault-calc:8200\", job=\"vault-calc\"}[$__rate_interval])) or vector (0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(vault_runtime_sys_bytes{instance=\"vault-calc:8200\", job=\"vault-calc\"}[5m]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de requisições ao Vault",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance) (vault_core_handle_request_sum{job=\"vault-calc\", instance=\"vault-calc:8200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status do seal (sealed/unsealed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "vault_core_unsealed{instance=\"vault-calc:8200\", cluster=\"vault-cluster-470928c5\", job=\"vault-calc\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}